syms delta theta thetadot deltadot
R_tb_t1=[0,cos(delta),sin(delta);...
    0,-sin(delta),cos(delta);...
    1,0,0];
R_t1_t2=[cos(theta),-sin(theta),0;...
    sin(theta),cos(theta),0;...
    0,0,1];
R_t2_te=[0,0,1;...
    cos(delta),-sin(delta),0;...
    sin(delta),cos(delta),0];
Jwv=[sin(delta),cos(delta)*sin(theta);...
    cos(delta),-sin(delta)*sin(theta);...
    0,cos(theta)-1];
psaidot=[thetadot;deltadot];
% simple(R_tb_t1*R_t1_t2*R_t2_te)
gri=R_tb_t1*R_t1_t2*R_t2_te*15*[0;0;1];
simple(cross(Jwv*psaidot,gri)); %验证continuum arm 加入gripper后Jcv第二项矩阵与该处计算结果是一致的

%验证单节arm的Jw
-deltadot*[0;0;1]+R_tb_t1*thetadot*[0;0;1]+R_tb_t1*R_t1_t2*deltadot*[1;0;0]
